from __future__ import annotations
from typing import Dict, Union, Optional, List, Any, TypeVar, Type

from .property import Property
from .prim_metadata import PrimMetadata
from .sdf import Specifier
from .common import SchemaKind
from .layer import Layer
from .model_api import ModelAPI
from .clips_api import ClipsAPI
from .collection_api import CollectionAPI
from .color_space_api import ColorSpaceAPI
from .color_space_definition_api import ColorSpaceDefinitionAPI


PrimType = TypeVar('PrimType', bound='Prim')

class Prim:
    
    schema_kind: SchemaKind = SchemaKind.ConcreteTyped
    meta: Dict[str, Any] = {}

    def __init__(self, name:str="", specifier:Specifier=Specifier.Def)->None: ...
    
    @property
    def specifier(self)->Specifier: ...
    
    @specifier.setter
    def specifier(self, specifier:Specifier)->None: ...

    def create_prop(self, prop:Property)->Property: ...

    def has_prop(self, name:str, recursive:bool=True, specialize:bool=True)->bool: ...

    def prop(self, name:str, recursive:bool=True, specialize:bool=True)->Property: ...

    def __getitem__(self, path:str)->Prim: ...

    def __setitem__(self, path:str, prim:Prim)->None: ...

    def __delitem__(self, path:str)->None: ...

    @property
    def prop_names(self)->List[str]: ...
    
    @property
    def props(self)->List[Property]: ...

    def child(self, name:str)->Prim: ...
    
    @property
    def children(self)->List[Prim]: ...
    
    @property
    def child_names(self)->List[str]: ...

    def add_child(self, prim:Prim)->None: ...

    def def_(self, prim_type:Type[PrimType], path:str)->PrimType: ...
    
    def class_(self, path:str)->Prim: ...
    
    def over_(self, path:str)->Prim: ...
    
    def inherit(self, prim:Union[Prim, Layer], prepend:bool=True)->None: ...

    def remove_inherit(self, prim:Union[Prim, Layer])->None: ...

    def reference(self, prim:Union[Prim, Layer], prepend:bool=True)->None: ...

    def remove_reference(self, prim:Union[Prim, Layer])->None: ...

    def payload(self, prim:Union[Prim, Layer], prepend:bool=True)->None: ...

    def remove_payload(self, prim:Union[Prim, Layer])->None: ...

    def specialize(self, prim:Union[Prim, Layer], prepend:bool=True)->None: ...

    def remove_specialize(self, prim:Union[Prim, Layer])->None: ...

    def remove_child(self, prim:Union[str, Prim])->Prim: ...

    def detach_from_parent(self)->None: ...

    def detach_from_layer(self)->None: ...

    @property
    def metadata(self)->PrimMetadata: ...

    @property
    def name(self)->str: ...

    @name.setter
    def name(self, name:str)->None: ...

    @property
    def parent(self)->Optional[Prim]: ...
    
    @property
    def layer(self)->Optional[Layer]: ...

    @property
    def path(self)->str: ...
    
    def id(self, rel_layer:Optional[Union[str, Layer]]=None)->str: ...

    def __eq__(self, other:Any)->bool: ...
    
    def __neq__(self, other:Any)->bool: ...

    @property
    def depth(self)->int: ...
    
    def __str__(self)->str: ...
    
    def to_str(self, indents:int=0)->str: ...
    
    @classmethod
    def cls_to_str(cls)->str: ...

    @property
    def model_api(self)->ModelAPI: ...

    @property
    def clips_api(self)->ClipsAPI: ...

    def collection_api(self, instance_name:str)->CollectionAPI: ...

    @property
    def color_space_api(self)->ColorSpaceAPI: ...

    @property
    def color_space_definition_api(self)->ColorSpaceDefinitionAPI: ...