from ..attribute_spec import AttributeSpec
from ..gf import Mat4Type, Vec3Type

class XformOp(AttributeSpec):

    def __init__(self)->None: ...

    @property
    def translate(self)->AttributeSpec: ...

    @translate.setter
    def translate(self, value:Vec3Type)->None: ...

    @property
    def rotateXYZ(self)->AttributeSpec: ...

    @rotateXYZ.setter
    def rotateXYZ(self, value:Vec3Type)->None: ...

    @property
    def rotateX(self)->AttributeSpec: ...

    @rotateX.setter
    def rotateX(self, value:float)->None: ...

    @property
    def rotateY(self)->AttributeSpec: ...

    @rotateY.setter
    def rotateY(self, value:float)->None: ...

    @property
    def rotateZ(self)->AttributeSpec: ...

    @rotateZ.setter
    def rotateZ(self, value:float)->None: ...

    @property
    def scale(self)->AttributeSpec: ...

    @scale.setter
    def scale(self, value:Vec3Type)->None: ...

    @property
    def transform(self)->AttributeSpec: ...

    @transform.setter
    def transform(self, value:Mat4Type)->None: ...
